### ISSUE TITLE
Resultados faltando 

### ISSUE THREAD

**Issue by igorSilCar** [unb-ppca-construcao-de-software-2016/dados-nivel-superior#24]
Busca por ciência da computação mão retorna resultados. Problema verificado com e sem acentos, parece ocorrer com qualquer busca por nome composto.

**Comment by rodolfocruzbsb** [comment]
Realizei a consulta com o parametro informado e foi retornado os resultados. @igorSilCar teste novamente por favor.

**Comment by igorSilCar** [comment]
@rodolfocruzbsb realizei novos testes e realmente o problema nao ocorre se a busca for realizada sem espacos no fim do texto e com acentos. Adicionei um trim a string de busca, vou tentar adicionar um regex.
